### ISSUE TITLE
Page View Support

### ISSUE THREAD

**Issue by gonzoknows** [tajacks/lightspeed#7]
Support for a privacy respecting page view counter

**Comment by tajacks** [comment]
Good idea. I'm a big fan of Plausible Analytics, so adding that for now. Future ideas welcome as long as they are privacy respecting.

**Comment by ghost** [comment]
> Good idea. I'm a big fan of Plausible Analytics, so adding that for now. Future ideas welcome as long as they are privacy respecting.

Glad you got a privacy focused jekyll repo
